### ISSUE TITLE
update with styles-es, import to swcarpentry

### ISSUE THREAD

**Issue by raynamharris** [carpentries/workshop-template-es#24]
I have used this template once and it worked pretty well. I think it needs the following two changes to be ready for production. cc @fmichonneau  

- [x] /_includes needs to be updated from styles-es
- [ ] should probably be moved to swcarpentry repo

**Comment by raynamharris** [comment]
Hi @fmichonneau I finally got around to syncing this with the styles repo to sync with all the translated syllabi and schedules. 

I worry that it might be out of sync with some new of the formatting in the english styles repo, but I don't want to attempt to fetch changes and override any translations...

What do you think?

Also, what do you think about migrating to github.com/swcarpentry?

**Comment by fmichonneau** [comment]
I'm going to migrate it to the carpentries organization as the other infrastructure repositories. 

We'll have a new release of the styles repository soon. It will be a good occasion to test potential merge conflicts with the translation. I think it's going to be OK, even if there will be some manual resolutions to do.

**Comment by raynamharris** [comment]
Awesome! Thanks @fmichonneau
